services:
  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_DB: clashofcode
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  backend:
    build: ./server
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/clashofcode
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ONECOMPILER_KEY: ${ONECOMPILER_KEY}
      GMAIL_USERNAME: ${GMAIL_USERNAME}
      GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}

  frontend:
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      - backend