spring.application.name=server
server.port=${PORT:8080}

logging.level.org.springframework.web=DEBUG
logging.level.com.server=DEBUG

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.max-lifetime=600000

spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.sql.init.platform=postgres

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=604800000

onecompiler.api.key=${ONECOMPILER_KEY}
onecompiler.api.url=https://onecompiler-apis.p.rapidapi.com/api/v1/run
onecompiler.api.host=onecompiler-apis.p.rapidapi.com

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.from=${GMAIL_USERNAME}
